### ISSUE TITLE
Update GitHub workflows to match the new organization

### ISSUE THREAD

**Issue by friedow** [i18next/i18next-vue#1]
Since this repository has been migrated, the GitHub workflows contained in it need to be updated to match the new organization information.

**Comment by friedow** [comment]
@adrai do we have an organization wide secret for publishing to npm? If so, could you share that secret with this repository? This is necessary to for the "publish to npm" workflow to work (https://github.com/i18next/vue-i18next/blob/main/.github/workflows/npm-publish.yml).

**Comment by adrai** [comment]
no we haven't, each repo/project manages this itself...

**Comment by friedow** [comment]
Ok thanks, I'm gonna setup this up for this repository then.

Btw: Since you do a lot of maintanance for this organization, you might wanna make your contribution to this organization public. (Check out your own profile in an incognito tab: https://github.com/adrai). Thats why I didn't know you are a maintainer here ;).

**Comment by adrai** [comment]
strange, it was set to private

**Comment by kkuegler** [comment]
I'm handling publishing to the npm registry manually for now, so I'll close this.
