### ISSUE TITLE
Please update for i18next > v22.5.0

### ISSUE THREAD

**Issue by dogrocker** [i18next/i18next-vue#14]
Hello! in `index.ts` have some error when using i18next >= v22.5.0

**Comment by kkuegler** [comment]
Hi @dogrocker 

can you provide a little more context, so its easier to identify the problem? Please provide the version of i18next-vue and Vue you are using, and the actual error message. If this is a TypeScript error, also the TS version would be helpful.

Does the problem occur when using i18next-vue in your code or do you see this when building i18next-vue itself?

**Comment by kkuegler** [comment]
Feel free to add more information. Until then I'll close this ticket.
