### ISSUE TITLE
[Typescript Error] useTranslation - Type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by hunterliu1003** [i18next/i18next-vue#18]
Hi, thank you for the awesome framework, it's so amazing!

## 🐛 Bug Report

I have two question:
- The first one is related to the type error
  I get the typescript error `Type instantiation is excessively deep and possibly infinite` while using `useTranslation` composable function in a Vue component. I've searched some similar issues but did not find the solution.
- I follow the youtube video to setup typescript for i18next: https://www.youtube.com/watch?v=GLIas4DH3Ww
  It seems doesn't work properly. 

## To Reproduce

https://stackblitz.com/edit/github-lup5wg?file=src%2Fcomponents%2FComponentTypeError.ts

Screenshot:
<img width="812" alt="image" src="https://github.com/i18next/i18next-vue/assets/15190246/7ac337a2-0a4e-4d69-a543-ad8c8d1e3a67">

Both `useTranslation()` and `t()` has the type error:
```ts
import { h, computed } from 'vue';
import { useTranslation } from 'i18next-vue';

export default {
  name: 'ComponentTypeError',
  setup() {
    // Here is the type error
    const { t } = useTranslation();

    // Here is the type error
    const insurance = computed(() => t('insurance'));

    return () => {
      return h('div', `inline => ${insurance.value}`);
    };
  },
};

```

## Expected behavior

- Should not cause typescript issues
- The autocompletion should work properly

## Your Environment

- *runtime version*: node v18(locally), stackbliz(node v18.8)
- *i18next version*: 23.5.1
- *i18next-vue*: 3.0.0
- *typescript*: 5.2.2
- *os*: Mac

**Comment by hunterliu1003** [comment]
Sorry it's my fault I missed the `typeof` in the following code: 
```ts
import Resources from './resources';

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: 'translation';
    resources: typeof Resources;
  }
}

```

**Comment by kkuegler** [comment]
Ah, no problem. Glad you figured it out already!
