### ISSUE TITLE
Unable to install via npm?

### ISSUE THREAD

**Issue by Xikura** [i18next/i18next-vue#2]
## 🐛 Bug Report

Unable to install using npm and install from zip / folder creates unexpected errors

## To Reproduce

- Have node.js v15 or higher
- Try "npm install i18next-vue"

## Expected behavior

For the module to be installed

## Actual behavior

NPM throws a 404 error message

## Your Environment

- *runtime version*: node v16.15.0
- *i18next version*: i.e. 21.8.0
- *os*: Mac

**Comment by kkuegler** [comment]
The package is now available via npm. So `npm install i18next-vue` should get you the (beta) package now.

Feel free to re-open if you still encounter problems 😃
